openapi: "3.0.0"

info:
  title: "ArticleCollection App"
  version: "1.0.0"

paths:
  "/api/v1/articles":
    post:
      summary: "記事情報を取得"
      tags: ["articles"]
      requestBody:
        description: "レビューの中身"
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                qiitaUserName: { type: string, example: "kamimi01" }
                noteUserName: { type: string, example: "kamikami" }
      responses:
        "200":
          description: "Success"
          headers:
            X-Rate-Limit:
              schema:
                type: integer
                example: 10
              description: "リクエスト上限回数"
            X-Rate-Remaining:
              schema:
                type: integer
                example: 4                
              description: "リクエスト可能回数"
          content:
            application/json:
              schema:
                type: object
                properties:
                  articleContents:
                    type: array
                    items:
                      type: object
                      properties:
                        service:
                          {
                            type: string,
                            description: "記事のサービス名",
                            example: "qiita",
                          }
                        articles:
                          type: array
                          items:
                            type: object
                            properties:
                              title:
                                {
                                  type: string,
                                  description: "記事タイトル",
                                  example: "clusterのリンクをまとめてみた",
                                }
                              userName:
                                {
                                  type: string,
                                  description: "ユーザ名",
                                  example: "kamimi01",
                                }
                              numOfGood:
                                {
                                  type: integer,
                                  description: "いいねやスキの数",
                                  example: 5,
                                }
                              url:
                                {
                                  type: string,
                                  description: "記事のURL",
                                  example: "https://qiita.com/kamimi01",
                                }
        "400":
          description: "Request Body is required"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrResponses"
        "415":
          description: "Unsupported Media Type"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrResponses"
        "429":
          description: "Too Many requests"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrResponses"
        "500":
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrResponses"

components:
  schemas:
    ErrResponses:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              type:
                {
                  type: string,
                  description: "エラーのタイプ",
                  example: "unsupported_content_type",
                }
              message:
                {
                  type: string,
                  description: "エラーメッセージ",
                  example: "Unsupported Content-Type",
                }
