openapi: "3.0.0"

info:
  title: "ArticleCollection App"
  version: "1.0.0"

paths:
  "/api/v1/articles":
    get:
      summary: "記事情報取得"
      tags: ["articles"]
      parameters:
        - name: qiitaUserName
          in: query
          description: QiitaユーザID
          required: false
          schema:
            type: string
          example: "kamimi01"
        - name: noteUserName
          in: query
          description: Noteユーザ名
          required: false
          schema:
            type: string
          example: "kamimi01"
      responses:
        "200":
          description: "Success"
          headers:
            X-Rate-Limit:
              schema:
                type: integer
                example: 10
              description: "リクエスト上限回数"
            X-Rate-Remaining:
              schema:
                type: integer
                example: 4                
              description: "リクエスト可能回数"
          content:
            application/json:
              schema:
                type: object
                properties:
                  articleContents:
                    type: array
                    items:
                      type: object
                      properties:
                        service:
                          {
                            type: string,
                            description: "記事のサービス名",
                            example: "qiita",
                          }
                        articles:
                          type: array
                          items:
                            type: object
                            properties:
                              title:
                                {
                                  type: string,
                                  description: "記事タイトル",
                                  example: "clusterのリンクをまとめてみた",
                                }
                              userName:
                                {
                                  type: string,
                                  description: "ユーザ名",
                                  example: "kamimi01",
                                }
                              numOfGood:
                                {
                                  type: integer,
                                  description: "いいねやスキの数",
                                  example: 5,
                                }
                              url:
                                {
                                  type: string,
                                  description: "記事のURL",
                                  example: "https://qiita.com/kamimi01",
                                }
        "400":
          description: "At least one prameter is required"
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          {
                            type: string,
                            description: "エラーのタイプ",
                            example: "no_parameters",
                          }
                        message:
                          {
                            type: string,
                            description: "エラーメッセージ",
                            example: "At least one prameter is required",
                          }
        "415":
          description: "Unsupported Media Type"
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          {
                            type: string,
                            description: "エラーのタイプ",
                            example: "unsupported_content_type",
                          }
                        message:
                          {
                            type: string,
                            description: "エラーメッセージ",
                            example: "Unsupported Content-Type",
                          }
        "429":
          description: "Too Many requests"
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          {
                            type: string,
                            description: "エラーのタイプ",
                            example: "too_many_requests",
                          }
                        message:
                          {
                            type: string,
                            description: "エラーメッセージ",
                            example: "Too Many requests",
                          }
        "500":
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          {
                            type: string,
                            description: "エラーのタイプ",
                            example: "internal_server_error",
                          }
                        message:
                          {
                            type: string,
                            description: "エラーメッセージ",
                            example: "Internal Server Error",
                          }

components:
  schemas:
    ErrResponses:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              type:
                {
                  type: string,
                  description: "エラーのタイプ",
                  example: "unsupported_content_type",
                }
              message:
                {
                  type: string,
                  description: "エラーメッセージ",
                  example: "Unsupported Content-Type",
                }
