openapi: "3.0.0"

info:
  title: "ArticleCollection App"
  version: "1.0.0"

paths:
  "/articles":
    get:
      summary: "記事情報取得"
      tags: ["articles"]
      parameters:
        - name: X-Api-Key
          in: header
          required: true
          schema:
            type: string
          example: "api-key"
        - name: userName
          in: query
          description: QiitaユーザID
          required: false
          schema:
            type: string
          example: "kamimi01"
      responses:
        "200":
          description: "Success"
          headers:
            X-Rate-Limit:
              schema:
                type: integer
                example: 10
              description: "リクエスト上限回数"
            X-Rate-Remaining:
              schema:
                type: integer
                example: 4                
              description: "リクエスト可能回数"
          content:
            application/json:
              schema:
                type: object
                properties:
                  articleContents:
                    type: array
                    items:
                      type: object
                      properties:
                        service:
                          {
                            type: string,
                            description: "記事のサービス名",
                            example: "qiita",
                          }
                        title:
                          {
                            type: string,
                            description: "記事タイトル",
                            example: "色んな人向けにバーチャルSNS - cluster - に関するリンクを広く浅くまとめてみた",
                          }
                        userName:
                          {
                            type: string,
                            description: "ユーザ名",
                            example: "kamimi01",
                          }
                        likesCount:
                          {
                            type: integer,
                            description: "いいねやスキの数",
                            example: 1,
                          }
                        profileImageUrl:
                          {
                            type: string,
                            description: "プロフィール画像",
                            example: "https://avatars1.githubusercontent.com/u/47489629?v=4"
                          }
                        url:
                          {
                            type: string,
                            description: "記事のURL",
                            example: "https://qiita.com/kamimi01/items/353ed9502ed62cbe9864",
                          }
                        createdDate:
                          {
                            type: string,
                            description: 記事の作成日時,
                            example: "2020-12-24T12:06:44+09:00" 
                          }
                              
        "400":
          description: "At least one prameter is required"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    {
                      type: string,
                      description: "エラーメッセージ",
                      example: "At least one prameter is required",
                    }                
                  type:
                    {
                      type: string,
                      description: "エラーのタイプ",
                      example: "no_parameters",
                    }
        "403":
          description: "Forbidden"
        "415":
          description: "Unsupported Media Type"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    {
                      type: string,
                      description: "エラーメッセージ",
                      example: "Unsupported Content-Type",
                    }                
                  type:
                    {
                      type: string,
                      description: "エラーのタイプ",
                      example: "unsupported_content_type",
                    }
        "429":
          description: "Too Many requests"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    {
                      type: string,
                      description: "エラーメッセージ",
                      example: "Too Many requests",
                    }
                  type:
                    {
                      type: string,
                      description: "エラーのタイプ",
                      example: "too_many_requests",
                    }   
        "500":
          description: "Internal Server Error"

components:
  schemas:
    ErrResponses:
      type: object
      properties:
        message:
          {
            type: string,
            description: "エラーメッセージ",
            example: "Unsupported Content-Type",
          }
        type:
          {
            type: string,
            description: "エラーのタイプ",
            example: "unsupported_content_type",
          }